### PR TITLE
Category search

### PR DESCRIPTION
**Pull request by Chasiwpaw**
#70 
I improved the currently searching algorithm, searching should now filter according to both search Input and category even though some of the keys are missing.

### CODE REVIEW

**Comment by Chasiwpaw** [comment]
Actually this pull request is also related to #75 task

**Comment by jeffbuonamici** [comment]
Is the search completely finished now?

**Comment by Chasiwpaw** [comment]
Should be, unless I am missing something. Try and test it, then let me know

**Comment by jeffbuonamici** [comment]
Looks good.

**Comment by MikeSmvl** [comment]
@jeffbuonamici @Chasiwpaw There is a slight issue when trying to open up the categories. It doesn't seem to open.

**Comment by darkheros12** [comment]
Same goes for me, the search category does not display anything. maybe its something wrong with the logic?

**Comment by MikeSmvl** [comment]
@darkheros12 @jeffbuonamici @Chasiwpaw The issue is now fixed and everything else works as intended. I am merging this branch!

**Pull request merged**
