### PR TITLE
Merging dev into Master

### PR DESCRIPTION
**Pull request by jeffbuonamici**
Tests were done in the dev branch with all the solved issues mostly related to registration and signing in features. Travis CI's build passed and we are ready to add these changes as our new stable master branch.

### CODE REVIEW

**Comment by jeffbuonamici** [comment]
We have a stable dev build with a week's work. So I think it's time we merge it into master.

**Comment by darkheros12** [comment]
The dev is working correctly for the 2nd springs. No bugs were found. This pull request should be merged into the master.

**Comment by MikeSmvl** [comment]
I've went through the code one more time and agree with @darkheros12 and @jeffbuonamici . All the issues that made up the dev branch are referenced and descriptive. I will merge the pull request tomorrow to make sure everyone is in agreement.

**Comment by Chasiwpaw** [comment]
I haven't had time to test the branch, I'll do so tonight and let you guys know

**Comment by Chasiwpaw** [comment]
The dev branch has been tested, the new features are working the way as described in the issues. Ready to be merged! 👍

**Pull request merged**
