### PR TITLE
Post ad functionality, and search bar component

### PR DESCRIPTION
**Pull request by jeffbuonamici**
Post Ad component was added to the navigation bar and linked to the page that has the form to post an ad. Functionality was added to be able to post the information about the ad to the firebase database.
A search bar element was added without functionality to begin the work related with this feature.
The sign in and registering pages were redesigned slightly.

### CODE REVIEW

**Comment by asoorkeea** [comment]
It seems there's an alert in the action.js

**Comment by jeffbuonamici** [comment]
@asoorkeea Please tell me what the error is. Everything is compiling properly on my end.

**Comment by MikeSmvl** [comment]
@jeffbuonamici Can we have the search bar show up only in the home page for now?

**Review by neha08585 — COMMENTED** [review]
Changes look good to me. I was able to test the changes locally. Good job.

**Comment by jeffbuonamici** [comment]
@MikeSmvl Done.

**Comment by neha08585** [comment]
Can we have a browse button to upload the image and pre-populated dropdown list for location?

**Comment by darkheros12** [comment]
Is this problem fixed yet?

**Comment by jeffbuonamici** [comment]
@darkheros12 There never was a problem. When he said "alert" I thought he meant error, but that's not the case. He was just stating that there's alert() dialog.

**Comment by Ruthvik-Shandilya** [comment]
Merging the Branch as it is appropriate and working accordingly.

**Pull request merged**
