### PR TITLE
Code coverage

### PR DESCRIPTION
**Pull request by Ruthvik-Shandilya**
This PR produces the code coverage report for our unit tests.

### CODE REVIEW

**Comment by Ruthvik-Shandilya** [comment]
There was an error in raising the initial PR , so now i have changed the base branch to dev.

**Comment by asoorkeea** [comment]
I made some modifications to the unit tests and based on the initial results of the code coverage which seems strange. The stats that we have now reflects more of our code base coverage.

**Comment by asoorkeea** [comment]
Please review and merge in the dev branch. The PR contains some refactoring in the actions.js layer namely
- moving some of the functions in the actions.ad.js.
- trying to remove the use of firebase api in this layer by moving the work load in the component actions.

It will impact all the other branches already created, all contributors will have to update their branches.

**Comment by darkheros12** [comment]
Is the code coverage cover all the unit test so it can be merged into the dev branch?

**Comment by Ruthvik-Shandilya** [comment]
Yes the coverage has completed for almost all of the test cases. We can merge into the dev branch.

**Comment by darkheros12** [comment]
We need at least three persons to approve this merged first and then the last one should merge it. It has my approval

**Comment by MikeSmvl** [comment]
There are some small conflicts that need to be resolved and then we can merge.

**Comment by asoorkeea** [comment]
Ok done.

**Pull request merged**
